package main

type commands struct {
	Name          string
	Install       string
	Uninstall     string
	Upgrade       string
	Search        string
	Info          string
	UpgradeAll    string
	ListInstalled string
}

var pm_commands = map[string]commands{
	"i": {
		Name:          "i",
		Install:       "i install x",
		Uninstall:     "i uninstall x",
		Upgrade:       "i upgrade x",
		Search:        "i search x",
		Info:          "i info x",
		UpgradeAll:    "i upgrade",
		ListInstalled: "i list",
	},
	"apt": {
		Name:          "apt",
		Install:       "apt install x",
		Uninstall:     "apt remove x",
		Upgrade:       "apt install --only-upgrade x",
		Search:        "apt search x",
		Info:          "apt show x",
		UpgradeAll:    "apt upgrade",
		ListInstalled: "apt list --installed", // apt list -i
	},
	"brew": {
		Name:          "brew",
		Install:       "brew install x",
		Uninstall:     "brew uninstall x",
		Upgrade:       "brew upgrade x",
		Search:        "brew search x",
		Info:          "brew info x",
		UpgradeAll:    "brew upgrade",
		ListInstalled: "brew list",
	},
	"port": {
		Name:          "port",
		Install:       "port install x",
		Uninstall:     "port uninstall x",
		Upgrade:       "port upgrade x",
		Search:        "port search x",
		Info:          "port info x",
		UpgradeAll:    "port upgrade",
		ListInstalled: "port installed",
	},
	"flatpak": {
		Name:          "flatpak",
		Install:       "flatpak install x",
		Uninstall:     "flatpak uninstall x",
		Upgrade:       "flatpak update x",
		Search:        "flatpak search x",
		Info:          "flatpak info x",
		UpgradeAll:    "flatpak update",
		ListInstalled: "flatpak list",
	},
	"snap": {
		Name:          "snap",
		Install:       "snap install --classic x", // --classic or not ?
		Uninstall:     "snap remove x",
		Upgrade:       "snap refresh x",
		Search:        "snap find x",
		Info:          "snap info x",
		UpgradeAll:    "snap refresh",
		ListInstalled: "snap list",
	},
	"dnf": {
		Name:          "dnf",
		Install:       "dnf install -y x",
		Uninstall:     "dnf remove -y x",
		Upgrade:       "dnf upgrade -y x",
		Search:        "dnf search x",
		Info:          "dnf info x",
		UpgradeAll:    "dnf upgrade -y",
		ListInstalled: "dnf list installed",
	},
	"rpm": {
		Name:          "rpm",
		Install:       "rpm -i x",
		Uninstall:     "rpm -e x",
		Upgrade:       "rpm -U x",
		Search:        "rpm -q x",
		Info:          "rpm -q x",
		UpgradeAll:    "rpm -Uvh x",
		ListInstalled: "rpm -qa",
	},
	"pacman": {
		Name:          "pacman",
		Install:       "pacman -S --noconfirm x",
		Uninstall:     "pacman -Rs --noconfirm x",
		Upgrade:       "pacman -Syu --noconfirm x", // Upgrade specific pkg and system? Usually just -S to reinstall/upgrade specific
		Search:        "pacman -Ss x",
		Info:          "pacman -Qi x",
		UpgradeAll:    "pacman -Syu --noconfirm",
		ListInstalled: "pacman -Q",
	},
	"yum": {
		Name:          "yum",
		Install:       "yum install -y x",
		Uninstall:     "yum remove -y x",
		Upgrade:       "yum update -y x",
		Search:        "yum search x",
		Info:          "yum info x",
		UpgradeAll:    "yum update -y",
		ListInstalled: "yum list installed",
	},
	"zypper": {
		Name:          "zypper",
		Install:       "zypper install -n x",
		Uninstall:     "zypper remove -n x",
		Upgrade:       "zypper update -n x",
		Search:        "zypper search x",
		Info:          "zypper info x",
		UpgradeAll:    "zypper update -n",
		ListInstalled: "zypper se --installed-only",
	},
	"apk": {
		Name:          "apk",
		Install:       "apk add x",
		Uninstall:     "apk del x",
		Upgrade:       "apk add --upgrade x",
		Search:        "apk search x",
		Info:          "apk info x",
		UpgradeAll:    "apk upgrade",
		ListInstalled: "apk info",
	},
	"xbps": {
		Name:          "xbps",
		Install:       "xbps-install -y x",
		Uninstall:     "xbps-remove -y x",
		Upgrade:       "xbps-install -u x",
		Search:        "xbps-query -Rs x",
		Info:          "xbps-query -R x", // Remote info? or local -f? assuming remote
		UpgradeAll:    "xbps-install -Suy",
		ListInstalled: "xbps-query -l",
	},
	"emerge": {
		Name:          "emerge",
		Install:       "emerge x",
		Uninstall:     "emerge -C x",
		Upgrade:       "emerge -u x",
		Search:        "emerge -s x",
		Info:          "emerge -S x",
		UpgradeAll:    "emerge -uDN @world",
		ListInstalled: "qlist -I", // needs portage-utils potentially
	},
	"nix-env": {
		Name:          "nix-env",
		Install:       "nix-env -iA nixpkgs.x",
		Uninstall:     "nix-env -e x",
		Upgrade:       "nix-env -u x",
		Search:        "nix-env -qaP x",
		Info:          "nix-env -qa --description x",
		UpgradeAll:    "nix-env -u",
		ListInstalled: "nix-env -q",
	},
	"pkg": {
		Name:          "pkg",
		Install:       "pkg install -y x",
		Uninstall:     "pkg delete -y x",
		Upgrade:       "pkg upgrade -y x",
		Search:        "pkg search x",
		Info:          "pkg info x",
		UpgradeAll:    "pkg upgrade -y",
		ListInstalled: "pkg info",
	},
	"winget": {
		Name:          "winget",
		Install:       "winget install x",
		Uninstall:     "winget uninstall x",
		Upgrade:       "winget upgrade x",
		Search:        "winget search x",
		Info:          "winget show x",
		UpgradeAll:    "winget upgrade",
		ListInstalled: "winget list",
	},
	"scoop": {
		Name:          "scoop",
		Install:       "scoop install x",
		Uninstall:     "scoop uninstall x",
		Upgrade:       "scoop update x",
		Search:        "scoop search x",
		Info:          "scoop info x",
		UpgradeAll:    "scoop update",
		ListInstalled: "scoop list",
	},
	"choco": {
		Name:          "choco",
		Install:       "choco install x",
		Uninstall:     "choco uninstall x",
		Upgrade:       "choco upgrade x",
		Search:        "choco search x",
		Info:          "choco info x",
		UpgradeAll:    "choco upgrade",
		ListInstalled: "choco list",
	},
	"urpm": {
		Name:          "urpm",
		Install:       "urpmi x",
		Uninstall:     "urpme x",
		Upgrade:       "urpmi --update x",
		Search:        "urpmq --search x",
		Info:          "urpmq --info x",
		UpgradeAll:    "urpmi --update",
		ListInstalled: "urpmq --list",
	},
	"slackpkg": {
		Name:          "slackpkg",
		Install:       "slackpkg install x",
		Uninstall:     "slackpkg remove x",
		Upgrade:       "slackpkg upgrade x",
		Search:        "slackpkg search x",
		Info:          "slackpkg info x",
		UpgradeAll:    "slackpkg upgrade",
		ListInstalled: "slackpkg list installed",
	},
	"prt-get": {
		Name:          "prt-get",
		Install:       "prt-get install x",
		Uninstall:     "prt-get remove x",
		Upgrade:       "prt-get upgrade x",
		Search:        "prt-get search x",
		Info:          "prt-get info x",
		UpgradeAll:    "prt-get upgrade",
		ListInstalled: "prt-get list installed",
	},
	"pkgman": {
		Name:          "pkgman",
		Install:       "pkgman -S x",
		Uninstall:     "pkgman -R x",
		Upgrade:       "pkgman -Syu x",
		Search:        "pkgman -Ss x",
		Info:          "pkgman -Qi x",
		UpgradeAll:    "pkgman -Syu",
		ListInstalled: "pkgman -Q",
	},
	"opkg": {
		Name:          "opkg",
		Install:       "opkg install x",
		Uninstall:     "opkg remove x",
		Upgrade:       "opkg upgrade x",
		Search:        "opkg search x",
		Info:          "opkg info x",
		UpgradeAll:    "opkg upgrade",
		ListInstalled: "opkg list-installed",
	},
	"eopkg": {
		Name:          "eopkg",
		Install:       "eopkg install x",
		Uninstall:     "eopkg remove x",
		Upgrade:       "eopkg upgrade x",
		Search:        "eopkg search x",
		Info:          "eopkg info x",
		UpgradeAll:    "eopkg upgrade",
		ListInstalled: "eopkg list-installed",
	},
	"guix": {
		Name:          "guix",
		Install:       "guix install x",
		Uninstall:     "guix remove x",
		Upgrade:       "guix upgrade x",
		Search:        "guix search x",
		Info:          "guix info x",
		UpgradeAll:    "guix upgrade",
		ListInstalled: "guix list",
	},
	"cards": {
		Name:          "cards",
		Install:       "cards install x",
		Uninstall:     "cards remove x",
		Upgrade:       "cards upgrade x",
		Search:        "cards search x",
		Info:          "cards info x",
		UpgradeAll:    "cards upgrade",
		ListInstalled: "cards list",
	},
}
